services:
  api:
    build:
      context: .
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings_DevFreelaCs: Server=DB;database=DevFreela;User Id=sa;Password=Devfr33la#;TrustServerCertificate=True
      Notifications__FromName: Junior
      Notifications__FromEmail: junior@junior.com
      Notifications__Password: junior
      Notifications__SmtpHost: notificationmailcacther
      Notifications__SmtpPort: 25
    command: bash start-dev.sh
    ports:
      - "5001:5001"
    networks:
      - dev-freela-net
    volumes:
      - .:/DevFreela
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-CU6-ubuntu-20.04
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Devfr33la#
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    networks:
      - dev-freela-net
  notificationmailcacther:
    image: tophfr/mailcatcher
    ports:
      - "1025:25"
      - "1080:80"
    networks:
      - dev-freela-net

networks:
  dev-freela-net:
    name: dev-freela-net
    external: true
